version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1997
      POSTGRES_DB: news_portal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d # Mount SQL scripts into the container

  go-api:
    build:
      context: ./api_net-http
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1997
      POSTGRES_DB: news_portal
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  express-api:
    build:
      context: ./express-microservice
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1997
      POSTGRES_DB: news-portal
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: